site_name: "MDL Library"
theme:
  name: "material"

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google
            merge_init_into_class: true


# Navigation structure for your documentation
nav:
  - Home: index.md
  - Online Coding: online.md
  - Variational Coding: variational.md
  - Latent Variable Probing: latent_var.md
  - Bayesian approach: bayes.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.betterem
  - pymdownx.tilde

extra_css:
  - assets/stylesheets/extra.css
