site_name: "MDL Library"
theme:
  name: "material"
  features:
    - content.code.annotate
  palette:
    primary: indigo
    accent: pink

nav:
  - Home: index.md
  - Online Coding: online.md
  - Variational Coding: variational.md
  - Latent Variable Probing: latent_var.md
  - Bayesian approach: bayes.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]
          options:
            show_signature_annotations: true
            docstring_style: google
            show_attributes: true
            signature_crossrefs: true
            modernize_annotations: true
            show_source: false
            members_order: 'source'
            show_if_no_docstring: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            merge_init_into_class: true
            heading_level: 3
            parameter_headings: true
            show_root_heading: true
          import:
            - url: https://docs.python-requests.org/en/master/objects.inv
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      pygments_style: monokai
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.betterem
  - pymdownx.tilde

extra_css:
  - assets/stylesheets/extra.css
